/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
import java.sql.*;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author REZKY
 */
public class DataDosen extends javax.swing.JFrame {
    KoneksiDtbase dbsetting;
    String driver,database, user,pass,userlogin;

    private DefaultTableModel tblModel;
    private ButtonGroup buttonGroup;

    String data[]=new String[4];
    /**
     * Creates new form DataDosen
     */
    public DataDosen() {
        initComponents();
        dbsetting=new KoneksiDtbase();
        driver=dbsetting.SettingPanel("DBDriver");
        database=dbsetting.SettingPanel("DBDatabase");
        user=dbsetting.SettingPanel("DBUsername");
        pass=dbsetting.SettingPanel("DBPassword");
        this.setSize(600,700);
        buttonGroup = new ButtonGroup();
        tblModel = getDefaultTableModel();
        tabel.setModel(tblModel);
        Tabel(tabel,new int[]{120,180,120,120});
        setDefaultTable();
        buttonGroup.add(rLaki);
        buttonGroup.add(rPerempuan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNIDN = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tNoTlp = new javax.swing.JTextField();
        rLaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Profile.png"))); // NOI18N
        jLabel1.setText("Data Dosen");

        bKembali.setBackground(new java.awt.Color(255, 255, 0));
        bKembali.setText("<=");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bKembali)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bKembali))
        );

        jLabel2.setText("NIDN");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("No Telepon");

        tNIDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNIDNActionPerformed(evt);
            }
        });

        rLaki.setText("Laki-laki");
        rLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLakiActionPerformed(evt);
            }
        });

        rPerempuan.setText("Perempuan");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bSimpan.setBackground(new java.awt.Color(0, 255, 0));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(0, 0, 255));
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bClear.setBackground(new java.awt.Color(255, 255, 51));
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 51, 51));
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(bSimpan)
                .addGap(47, 47, 47)
                .addComponent(bUbah)
                .addGap(55, 55, 55)
                .addComponent(bClear)
                .addGap(43, 43, 43)
                .addComponent(bHapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bUbah)
                    .addComponent(bClear)
                    .addComponent(bHapus))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIDN", "Nama", "Jenis Kelamin", "No Telepon"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rLaki)
                                .addGap(18, 18, 18)
                                .addComponent(rPerempuan))
                            .addComponent(tNoTlp, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(tNama)
                            .addComponent(tNIDN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rLaki)
                    .addComponent(rPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNIDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNIDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNIDNActionPerformed

    private void rLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLakiActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        if(inputValid() == true) {
        String jenkel = "";
        if(rLaki.isSelected())
            jenkel = "Laki-Laki";
        else
            jenkel = "Perempuan";
        
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            
            // Menggunakan PreparedStatement untuk mencegah SQL Injection
            String SQL = "INSERT INTO dosen (nidn, nama, jenkel, notlp) VALUES (?, ?, ?, ?)";
            PreparedStatement pstmt = kon.prepareStatement(SQL);
            pstmt.setString(1, tNIDN.getText());
            pstmt.setString(2, tNama.getText());
            pstmt.setString(3, jenkel);
            pstmt.setString(4, tNoTlp.getText());

            pstmt.executeUpdate();

            // Menyiapkan data untuk ditampilkan di tabel
            data[0] = tNIDN.getText();
            data[1] = tNama.getText();
            data[2] = jenkel;
            data[3] = tNoTlp.getText();

            // Pastikan variabel 'row' terdefinisi dan memiliki nilai yang benar
            
            tblModel.insertRow(row, data);

            pstmt.close();
            kon.close();
        } catch(SQLException exc) {
            System.err.println("SQL Error: " + exc.getMessage());
        } catch(Exception exc) {
            System.err.println("Error: " + exc.getMessage());
        }
        bersih(); // Pastikan metode bersih() sudah didefinisikan
    }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        if(inputValid()==true){
            try{
                String jenkel="";
                if(rLaki.isSelected())
                    jenkel="Laki-Laki";
                else
                    jenkel="Perempuan";
                    Class.forName(driver);
                    Connection kon=DriverManager.getConnection(database,user,pass);
                    Statement stt=kon.createStatement();
                    String SQL="update dosen set nama='"+tNama.getText()+"',jenkel='"
                            +jenkel+"', notlp='"+tNoTlp.getText()+ 
                            "' where nidn='"+tNIDN.getText()+"'";
                    
                    stt.executeUpdate(SQL);
                    data[0]=tNIDN.getText();
                    data[1]=tNama.getText();
                    data[2]=jenkel;
                    data[3]=tNoTlp.getText();
                    tblModel.removeRow(row);
                    tblModel.insertRow(row, data);
                    stt.close();
                    kon.close();
                    
            } catch(Exception exc){
                System.err.println(exc.getMessage());
            }
            bersih();
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        tNIDN.setText("");
        tNama.setText("");
        tNoTlp.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
         if (tNIDN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang akan dihapus terlebih dahulu.");
            return;
        }

        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "DELETE FROM dosen WHERE nidn = '" + tNIDN.getText() + "'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
           
            
            stt.close();
        } catch (Exception exc) {
            System.err.println(exc.getMessage());
        }
        
        bersih();
    }//GEN-LAST:event_bHapusActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // TODO add your handling code here:
            Menu x = new Menu(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_bKembaliActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount ()==2){
            Tampil();
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void setDefaultTable() {
    String stat = "";
    Object[] data = new Object[4]; // Pastikan ukuran sesuai dengan jumlah kolom
    try {
        Class.forName(driver);
        Connection kon = DriverManager.getConnection(database, user, pass);
        Statement stt = kon.createStatement();
        String SQL = "SELECT * FROM dosen";
        ResultSet res = stt.executeQuery(SQL);
        
        while (res.next()) {
            data[0] = res.getString(1);
            data[1] = res.getString(2);
            data[2] = res.getString(3);
            data[3] = res.getString(4);
            tblModel.addRow(data);
            // Cetak data untuk debug
            System.out.println(Arrays.toString(data));
        }
        
        res.close();
        stt.close();
        kon.close();
    } catch (Exception exc) {
        System.err.println(exc.getMessage());
    }
}

private void Tabel(javax.swing.JTable tb, int lebar[]) {
    tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
    int kolom = tb.getColumnCount();
    for (int i = 0; i < kolom; i++) {
        javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
        tbc.setPreferredWidth(lebar[i]);
    }
    tb.setRowHeight(17); // Pindahkan di luar loop
}
    
    private void bersih(){
        tNIDN.setText("");
        tNama.setText("");
        rLaki.setSelected(false);
        rPerempuan.setSelected(false);
        tNoTlp.setText("");
        tNIDN.requestFocus();
    }
    
    private boolean inputValid() {
    boolean result;
    
    if (tNIDN.getText().equals("") || tNama.getText().equals("")|| tNoTlp.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Isi data yang dibutuhkan");
        result = false;
    } else {
        result = true;
    }
    
    return result;
}

    
  private javax.swing.table.DefaultTableModel getDefaultTableModel() {
    return new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"nidn", "nama", "jenis Kelamin", "notlp"}) {
                
        final boolean[] canEdit = new boolean[]{false, false, false, false};
        
        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };
}
   int row=0;
    public void Tampil(){
        row=tabel.getSelectedRow();
        tNIDN.setText(tblModel.getValueAt(row,0).toString());
        tNama.setText(tblModel.getValueAt(row,1).toString());
        if(tblModel.getValueAt(row,2).toString().equals("Laki-Laki")){
            rLaki.setSelected(true);
        }else{
            rPerempuan.setSelected(true);
        }
        tNoTlp.setText(tblModel.getValueAt(row,3).toString());
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rLaki;
    private javax.swing.JRadioButton rPerempuan;
    private javax.swing.JTextField tNIDN;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNoTlp;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
