/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
import java.sql.*;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author REZKY
 */
public class DataKelas extends javax.swing.JFrame {
    KoneksiDtbase dbsetting;
    String driver,database, user,pass,userlogin;

    private DefaultTableModel tblModel;

    String data[]=new String[4];
    /**
     * Creates new form DataKelas
     */
    public DataKelas() {
        initComponents();
        dbsetting=new KoneksiDtbase();
        driver=dbsetting.SettingPanel("DBDriver");
        database=dbsetting.SettingPanel("DBDatabase");
        user=dbsetting.SettingPanel("DBUsername");
        pass=dbsetting.SettingPanel("DBPassword");
        this.setSize(600,700);
        tblModel = getDefaultTableModel();
        tabel.setModel(tblModel);
        Tabel(tabel,new int[]{120,180,120,120});
        setDefaultTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tKdKelas = new javax.swing.JTextField();
        tNmKelas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        bKembali.setBackground(new java.awt.Color(255, 255, 0));
        bKembali.setText("<=");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Kelas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bKembali)
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bKembali)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setText("Kode Kelas");

        jLabel3.setText("Nama Kelas");

        tKdKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKdKelasActionPerformed(evt);
            }
        });

        tNmKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNmKelasActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        bSimpan.setBackground(new java.awt.Color(0, 255, 0));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(0, 0, 255));
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bClear.setBackground(new java.awt.Color(255, 255, 51));
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 0, 0));
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bSimpan)
                .addGap(26, 26, 26)
                .addComponent(bUbah)
                .addGap(29, 29, 29)
                .addComponent(bClear)
                .addGap(18, 18, 18)
                .addComponent(bHapus)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bUbah)
                    .addComponent(bClear)
                    .addComponent(bHapus))
                .addContainerGap())
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode Kelas", "Nama Kelas"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tKdKelas)
                            .addComponent(tNmKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tKdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNmKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // TODO add your handling code here:
            Menu x = new Menu(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_bKembaliActionPerformed

    private void tKdKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKdKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKdKelasActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
         if(inputValid() == true) {
        
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            
            // Menggunakan PreparedStatement untuk mencegah SQL Injection
            String SQL = "INSERT INTO kelas (kdkelas, nmkelas) VALUES (?, ?)";
            PreparedStatement pstmt = kon.prepareStatement(SQL);
            pstmt.setString(1, tKdKelas.getText());
            pstmt.setString(2, tNmKelas.getText());

            pstmt.executeUpdate();

            // Menyiapkan data untuk ditampilkan di tabel
            data[0] = tKdKelas.getText();
            data[1] = tNmKelas.getText();
           

            // Pastikan variabel 'row' terdefinisi dan memiliki nilai yang benar
            
            tblModel.insertRow(row, data);

            pstmt.close();
            kon.close();
        } catch(SQLException exc) {
            System.err.println("SQL Error: " + exc.getMessage());
        } catch(Exception exc) {
            System.err.println("Error: " + exc.getMessage());
        }
        bersih(); // Pastikan metode bersih() sudah didefinisikan
    }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        if(inputValid()==true){
            try{
           
                    Class.forName(driver);
                    Connection kon=DriverManager.getConnection(database,user,pass);
                    Statement stt=kon.createStatement();
                    String SQL="update kelas set nmkelas='"+tNmKelas.getText()+
                            "' where kdkelas='"+tKdKelas.getText()+"'";
                    
                    stt.executeUpdate(SQL);
                    data[0]=tKdKelas.getText();
                    data[1]=tNmKelas.getText();
                   
                    tblModel.removeRow(row);
                    tblModel.insertRow(row, data);
                    stt.close();
                    kon.close();
                    
            } catch(Exception exc){
                System.err.println(exc.getMessage());
            }
            bersih();
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        tKdKelas.setText("");
        tNmKelas.setText("");
        
    }//GEN-LAST:event_bClearActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
          if (tKdKelas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang akan dihapus terlebih dahulu.");
            return;
        }

        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "DELETE FROM kelas WHERE kdkelas = '" + tKdKelas.getText() + "'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
           
            
            stt.close();
        } catch (Exception exc) {
            System.err.println(exc.getMessage());
        }
        
        bersih();
    }//GEN-LAST:event_bHapusActionPerformed

    private void tNmKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNmKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNmKelasActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
           if(evt.getClickCount ()==2){
            Tampil();
        }
    }//GEN-LAST:event_tabelMouseClicked
     private void setDefaultTable() {
    String stat = "";
    Object[] data = new Object[2]; // Pastikan ukuran sesuai dengan jumlah kolom
    try {
        Class.forName(driver);
        Connection kon = DriverManager.getConnection(database, user, pass);
        Statement stt = kon.createStatement();
        String SQL = "SELECT * FROM kelas";
        ResultSet res = stt.executeQuery(SQL);
        
        while (res.next()) {
            data[0] = res.getString(1);
            data[1] = res.getString(2);
            tblModel.addRow(data);
            // Cetak data untuk debug
            System.out.println(Arrays.toString(data));
        }
        
        res.close();
        stt.close();
        kon.close();
    } catch (Exception exc) {
        System.err.println(exc.getMessage());
    }
}

private void Tabel(javax.swing.JTable tb, int lebar[]) {
    tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
    int kolom = tb.getColumnCount();
    for (int i = 0; i < kolom; i++) {
        javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
        tbc.setPreferredWidth(lebar[i]);
    }
    tb.setRowHeight(17); // Pindahkan di luar loop
}
    
    private void bersih(){
        tKdKelas.setText("");
        tNmKelas.setText("");
       
    }
    
    private boolean inputValid() {
    boolean result;
    
    if (tKdKelas.getText().equals("") || tNmKelas.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Isi data yang dibutuhkan");
        result = false;
    } else {
        result = true;
    }
    
    return result;
}

    
  private javax.swing.table.DefaultTableModel getDefaultTableModel() {
    return new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"KdKelas", "NmKelas"}) {
                
        final boolean[] canEdit = new boolean[]{false, false, false, false};
        
        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };
}
   int row=0;
    public void Tampil(){
        row=tabel.getSelectedRow();
        tKdKelas.setText(tblModel.getValueAt(row,0).toString());
        tNmKelas.setText(tblModel.getValueAt(row,1).toString());
       
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tKdKelas;
    private javax.swing.JTextField tNmKelas;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
