/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
import java.sql.*;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author REZKY
 */
public class DataMatkul extends javax.swing.JFrame {
        KoneksiDtbase dbsetting;
        String driver,database, user,pass,userlogin;
        String data[]=new String[4];
        private DefaultTableModel tblModel;
    /**
     * Creates new form DataMatkul
     */
    public DataMatkul() {
        initComponents();
        dbsetting=new KoneksiDtbase();
        driver=dbsetting.SettingPanel("DBDriver");
        database=dbsetting.SettingPanel("DBDatabase");
        user=dbsetting.SettingPanel("DBUsername");
        pass=dbsetting.SettingPanel("DBPassword");
        tblModel = getDefaultTableModel(); // Inisialisasi model tabel
        table.setModel(tblModel); // Set model ke JTable
        setDefaultTable(); 
        System.out.println("Model tabel terhubung dengan JTable.");
        table.repaint();
        Tabel(table,new int[]{120,180,120,120});
        this.setSize(600,700);
        
       
        setDefaultTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tKdMatkul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tNmMatkul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbSemester = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tSks = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Mata Kuliah");

        bKembali.setBackground(new java.awt.Color(255, 255, 102));
        bKembali.setText("<=");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bKembali)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(bKembali))
                .addGap(26, 26, 26))
        );

        jLabel2.setText("Kode Matkul");

        tKdMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKdMatkulActionPerformed(evt);
            }
        });

        jLabel3.setText("Jumlah SKS");

        tNmMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNmMatkulActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Matkul");

        jLabel5.setText("Semester");

        cbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSemesterActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        bSimpan.setBackground(new java.awt.Color(0, 255, 51));
        bSimpan.setForeground(new java.awt.Color(51, 51, 51));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(51, 51, 255));
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 51, 51));
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bClear.setBackground(new java.awt.Color(255, 255, 102));
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(bSimpan)
                .addGap(33, 33, 33)
                .addComponent(bUbah)
                .addGap(37, 37, 37)
                .addComponent(bHapus)
                .addGap(35, 35, 35)
                .addComponent(bClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bUbah)
                    .addComponent(bHapus)
                    .addComponent(bClear))
                .addContainerGap())
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Matkul", "Nama Matkul", "Jumlah SKS", "Semester"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);

        tSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tSks, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(tNmMatkul)
                            .addComponent(tKdMatkul)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tKdMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNmMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tKdMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKdMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKdMatkulActionPerformed

    private void tNmMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNmMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNmMatkulActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
           if (inputValid()) {
    Connection kon = null;
    Statement stt = null;
    try {
        Class.forName(driver);
        kon = DriverManager.getConnection(database, user, pass);
        stt = kon.createStatement();

        // Menggunakan PreparedStatement untuk mencegah SQL Injection
        String SQL = "UPDATE matkul SET nama_matkul = ?, jmlsks = ?, semester = ? WHERE kdMatkul = ?";
        PreparedStatement pstmt = kon.prepareStatement(SQL);
        pstmt.setString(1, tNmMatkul.getText());
        String tSks = "5"; // Deklarasi sebagai String
        pstmt.setString(2, tSks); // Pastikan tSks adalah String atau diubah menjadi format yang sesuai
        pstmt.setString(3, cbSemester.getSelectedItem().toString());
        pstmt.setString(4, tKdMatkul.getText());

        pstmt.executeUpdate();

        // Mengupdate data pada tabel model
        data[0] = tKdMatkul.getText();
        data[1] = tNmMatkul.getText();
        data[2] = tSks;
        data[3] = cbSemester.getSelectedItem().toString();
        tblModel.removeRow(row);
        tblModel.insertRow(row, data);

    } catch (Exception exc) {
        System.err.println(exc.getMessage());
    } finally {
        try {
            if (stt != null) stt.close();
            if (kon != null) kon.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    bersih();
}
    }//GEN-LAST:event_bUbahActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
       if (inputValid()) {
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);

            // Menggunakan PreparedStatement untuk mencegah SQL Injection
            String SQL = "INSERT INTO matkul (kdMatkul, nama_matkul, jmlsks, semester) VALUES (?, ?, ?, ?)";
            PreparedStatement pstmt = kon.prepareStatement(SQL);
            pstmt.setString(1, tKdMatkul.getText());
            pstmt.setString(2, tNmMatkul.getText());
            pstmt.setString(3, tSks.getText());
            pstmt.setString(4, cbSemester.getSelectedItem().toString());

            pstmt.executeUpdate();

            // Menyiapkan data untuk ditampilkan di tabel
            Object[] data = new Object[4];
            data[0] = tKdMatkul.getText();
            data[1] = tNmMatkul.getText();
            data[2] = tSks;
            data[3] = cbSemester.getSelectedItem().toString();

            // Tambahkan data ke tabel
            tblModel.addRow(data);

            // Tutup koneksi
            pstmt.close();
            kon.close();

        } catch (SQLException exc) {
            System.err.println("SQL Error: " + exc.getMessage());
        } catch (Exception exc) {
            System.err.println("Error: " + exc.getMessage());
        }
        bersih(); // Membersihkan input setelah menyimpan
    }
    }//GEN-LAST:event_bSimpanActionPerformed

     private void setDefaultTable() {
    String stat = "";
    Object[] data = new Object[4]; // Pastikan ukuran sesuai dengan jumlah kolom
    try {
        Class.forName(driver);
        Connection kon = DriverManager.getConnection(database, user, pass);
        Statement stt = kon.createStatement();
        String SQL = "SELECT * FROM matkul";
        ResultSet res = stt.executeQuery(SQL);

        // Kosongkan model tabel sebelum menambahkan data baru
        tblModel.setRowCount(0);

        int rowCount = 0;
        while (res.next()) {
            data[0] = res.getString(1);
            data[1] = res.getString(2);
            data[2] = res.getString(3);
            data[3] = res.getString(4);
            tblModel.addRow(data);
            rowCount++;
        }
        System.out.println("Jumlah data yang ditambahkan ke tabel: " + rowCount);

        res.close();
        stt.close();
        kon.close();
    } catch (Exception exc) {
        System.err.println(exc.getMessage());
    }

    // Perbarui tampilan tabel
    table.revalidate();
    table.repaint();
}


private void Tabel(javax.swing.JTable tb, int lebar[]) {
    tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
    int kolom = tb.getColumnCount();
    for (int i = 0; i < kolom; i++) {
        javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
        tbc.setPreferredWidth(lebar[i]);
    }
    tb.setRowHeight(17); // Pindahkan di luar loop
}
    
    private void bersih(){
        tKdMatkul.setText("");
        tNmMatkul.setText("");
        tSks.setText("");
        tKdMatkul.requestFocus();
    }
    
    private boolean inputValid() {
    boolean result;
    
    if (tKdMatkul.getText().equals("") || tNmMatkul.getText().equals("")|| tSks.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Isi data yang dibutuhkan");
        result = false;
    } else {
        result = true;
    }
    
    return result;
}
    
   private javax.swing.table.DefaultTableModel getDefaultTableModel() {
    return new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"kdMatkul", "NmMatkul", "jmlsks", "semester"}) {

        final boolean[] canEdit = new boolean[]{false, false, false, false};

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };
}
    
      int row=0;
    public void Tampil(){
        row=table.getSelectedRow();
        tKdMatkul.setText(tblModel.getValueAt(row,0).toString());
        tNmMatkul.setText(tblModel.getValueAt(row,1).toString());
        tSks.setText(tblModel.getValueAt(row,2).toString());
        cbSemester.setSelectedItem(tblModel.getValueAt(row,3).toString());
        
    }

    
    private void cbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSemesterActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
           if (inputValid() == true) {
        // Cek apakah ada data yang dipilih
        if (tKdMatkul.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang akan dihapus terlebih dahulu.");
            return;
        }

        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "DELETE FROM matkul WHERE kdMatkul = '" + tKdMatkul.getText() + "'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
            
            stt.close();
        } catch (Exception exc) {
            System.err.println(exc.getMessage());
        }
        
        bersih();
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        tNmMatkul.setText("");
        tKdMatkul.setText("");
        tSks.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // TODO add your handling code here:
            Menu x = new Menu(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_bKembaliActionPerformed

    private void tSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSksActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount ()==2){
            Tampil();
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMatkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField tKdMatkul;
    private javax.swing.JTextField tNmMatkul;
    private javax.swing.JTextField tSks;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
