/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author REZKY
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        bExit = new javax.swing.JMenuItem();
        mMaster = new javax.swing.JMenu();
        bDataMhs = new javax.swing.JMenuItem();
        bDataDosen = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        bDataMatkul = new javax.swing.JMenuItem();
        mEntryData = new javax.swing.JMenu();
        bInputAbsen = new javax.swing.JMenuItem();
        mLapMhs = new javax.swing.JMenu();
        lMhs = new javax.swing.JMenuItem();
        lDos = new javax.swing.JMenuItem();
        lKls = new javax.swing.JMenuItem();
        lMatkul = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        bKeluar = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/darkbg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        mFile.setText("File");
        mFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFileActionPerformed(evt);
            }
        });

        bExit.setText("Keluar");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        mFile.add(bExit);

        jMenuBar1.add(mFile);

        mMaster.setText("Master");
        mMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMasterActionPerformed(evt);
            }
        });

        bDataMhs.setText("Data Mahasiswa");
        bDataMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataMhsActionPerformed(evt);
            }
        });
        mMaster.add(bDataMhs);

        bDataDosen.setText("Data Dosen");
        bDataDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataDosenActionPerformed(evt);
            }
        });
        mMaster.add(bDataDosen);

        jMenuItem1.setText("Data Kelas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mMaster.add(jMenuItem1);

        bDataMatkul.setText("Data Mata Kuliah");
        bDataMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataMatkulActionPerformed(evt);
            }
        });
        mMaster.add(bDataMatkul);

        jMenuBar1.add(mMaster);

        mEntryData.setText("Entry Data");
        mEntryData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEntryDataActionPerformed(evt);
            }
        });

        bInputAbsen.setText("Input Absen");
        bInputAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInputAbsenActionPerformed(evt);
            }
        });
        mEntryData.add(bInputAbsen);

        jMenuBar1.add(mEntryData);

        mLapMhs.setText("Laporan");
        mLapMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLapMhsActionPerformed(evt);
            }
        });

        lMhs.setText("Laporan Mahasiswa");
        lMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lMhsActionPerformed(evt);
            }
        });
        mLapMhs.add(lMhs);

        lDos.setText("Laporan Dosen");
        lDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lDosActionPerformed(evt);
            }
        });
        mLapMhs.add(lDos);

        lKls.setText("Laporan Kelas");
        lKls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lKlsActionPerformed(evt);
            }
        });
        mLapMhs.add(lKls);

        lMatkul.setText("Laporan Matkul");
        lMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lMatkulActionPerformed(evt);
            }
        });
        mLapMhs.add(lMatkul);

        jMenuBar1.add(mLapMhs);

        jMenu1.setText("Keluar");

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(bKeluar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bExitActionPerformed

    private void bDataMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataMhsActionPerformed
        // TODO add your handling code here:
            DataMahasiswa x = new DataMahasiswa(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_bDataMhsActionPerformed

    private void bDataDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataDosenActionPerformed
        // TODO add your handling code here:
            DataDosen x = new DataDosen(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_bDataDosenActionPerformed

    private void bDataMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataMatkulActionPerformed
        // TODO add your handling code here:
            DataMatkul x = new DataMatkul(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_bDataMatkulActionPerformed

    private void bInputAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInputAbsenActionPerformed
        // TODO add your handling code here:
            DataKehadiran x = new DataKehadiran(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_bInputAbsenActionPerformed

    private void mFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mFileActionPerformed

    private void mMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mMasterActionPerformed

    private void mEntryDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEntryDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEntryDataActionPerformed

    private void mLapMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLapMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mLapMhsActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
         int a;
        a = JOptionPane.showConfirmDialog(null,
                "Apakah Yakin Akan Keluar Dari Aplikasi ini ?", "Keluar",
                JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION){
            //System.exit(0);
            this.dispose(); 
        }
    }//GEN-LAST:event_bKeluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
            DataKelas x = new DataKelas(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void lMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lMhsActionPerformed
        // TODO add your handling code here:
            FRepMhs x = new FRepMhs(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_lMhsActionPerformed

    private void lDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lDosActionPerformed
        // TODO add your handling code here:
            FRepDos x = new FRepDos(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_lDosActionPerformed

    private void lKlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lKlsActionPerformed
        // TODO add your handling code here:
        FRepKls x = new FRepKls(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_lKlsActionPerformed

    private void lMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lMatkulActionPerformed
        // TODO add your handling code here:
        FRepMatkul x = new FRepMatkul(); 
            this.setVisible(false);
            x.setVisible(true);
    }//GEN-LAST:event_lMatkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bDataDosen;
    private javax.swing.JMenuItem bDataMatkul;
    private javax.swing.JMenuItem bDataMhs;
    private javax.swing.JMenuItem bExit;
    private javax.swing.JMenuItem bInputAbsen;
    private javax.swing.JMenuItem bKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem lDos;
    private javax.swing.JMenuItem lKls;
    private javax.swing.JMenuItem lMatkul;
    private javax.swing.JMenuItem lMhs;
    private javax.swing.JMenu mEntryData;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mLapMhs;
    private javax.swing.JMenu mMaster;
    // End of variables declaration//GEN-END:variables
}

